# Deepin Project Downloader plugin files
deepin-project-downloader/deepin-project-downloader.desktop usr/share/deepin/dde-file-manager/oem-menuextensions
deepin-project-downloader/deepin-project-downloader.desktop usr/share/applications
deepin-project-downloader/deepin-project-downloader-launcher.sh usr/bin
deepin-project-downloader/deepin-project-downloader.svg usr/share/dfm-tools-plugins
deepin-project-downloader/deepin-project-downloader-backen.py usr/share/dfm-tools-plugins